# Travis CI

language: c

compiler:
  - gcc
  - clang

before_install:
  - sudo apt-get install -qq gettext

before_script:
  - env | sort
  - uname -a
  - chmod +x sweetbuild.sh
  - chmod +x sweetupload.sh

script:
  - "./sweetbuild.sh"
  
after_success:
  - "./sweetupload.sh"

env:
  global:
    secure: XpR/LSlRxEKT4WPYtl3t8ESKeNdzaQMEhrYBO1keDJaWI19DhTayd5bqX2E4R3+9CHKcb3oHqNuVMgu4pogr1wcfTDTB3KaAXIFVw53BblwQnJ19kq34FxMPqhKku8Il+XaYnp7iRpoKfhdrgEags8MIXd1mVFKYIWPc/Fq9aJ0=
